export enum LOCALVALUES {
  VERIFICATION_EMAIL = 'VERIFICATION_EMAIL',
  REMEMBER_EMAIL = 'REMEMBER_EMAIL',
  REMEMBER_PASSWORD = 'REMEMBER_PASSWORD',
  IS_REMEMBER = 'IS_REMEMBER',
  USER = 'USER',
  TOKEN_EXPIRY = 'TOKEN_EXPIRY',
  REFRESH_TOKEN = "REFRESH_TOKEN",
}


